namespace: todo
host: sc-todo.nl

database:
  image: mysql:8.0
  name: mysqldb
  user: mysqladmin
  host: mysql-service
  rootPassword: YWRtaW4= # admin
  password: YWRtaW4= # admin
  hostPath: "/opt/mysql/data"
  port: 3306
  labelApp: mysql
  storageClassName: standard

api:
  serviceName: todo-api-service
  serviceType: NodePort
  labelApp: todo-api
  image: gcr.io/todo-303012/todo-api:v1.2
  port: 8080
  targetPort: 8080
  replicas: 3
  uriPrefix: /api
  url: https://sc-todo.nl/api

frontend:
  serviceName: todo-frontend-service
  serviceType: NodePort
  labelApp: todo-frontend
  image: gcr.io/todo-303012/todo-frontend:v1
  port: 80
  targetPort: 80
  replicas: 3
  uriPrefix: /
  
tls:
  email: example@gmail.com
  issuerName: ca-issuer
  issuerKind: ClusterIssuer
  secretName: ca-secret
