namespace: todo

database:
  image: mysql:8.0
  name: mysqldb
  user: mysqladmin
  host: mysql-service
  rootPassword: YWRtaW4= # admin
  password: YWRtaW4= # admin
  hostPath: "/opt/mysql/data"
  port: 3306
  labelApp: mysql
  storageClassName: standard

api:
  serviceName: todo-api-service
  labelApp: todo-api
  image: gcr.io/todo-303012/todo-api:v1.2
  clusterIpPort: 8080
  clusterIpTargetPort: 8080
  replicas: 3
  uriPrefix: /api
  url: http://istio.sc-todo.nl/api

frontend:
  serviceName: todo-api-frontend
  labelApp: todo-frontend
  image: gcr.io/todo-303012/todo-frontend:v1
  canaryImage: gcr.io/todo-303012/todo-frontend:v2
  clusterIpPort: 8091
  clusterIpTargetPort: 80
  replicas: 3
  uriPrefix: /
  
istio:
  host: todo-app.com
  gateway:
    name: todo-app-gateway
    externalPort: 80
  appVirtualService:
    host: istio.sc-todo.nl

prometheus:
  host: prometheus.sc-todo.nl
  istioHost: prometheus.istio.sc-todo.nl
  serviceName: prometheus
  clusterIpPort: 9090
  
tls:
  issuerName: selfsigned-issuer
  issuerKind: Issuer
  secretName: selfsigned-secret
