namespace: todo

database:
  image: mysql:8.0
  name: mysqldb
  user: mysqladmin
  host: mysql-service
  rootPassword: YWRtaW4= # admin
  password: YWRtaW4= # admin
  hostPath: "/opt/mysql/data"
  port: 3306
  labelApp: mysql

api:
  serviceName: todo-api-service
  labelApp: todo-api
  image: localhost:32000/todo-api:v1
  clusterIpPort: 8080
  clusterIpTargetPort: 8080
  replicas: 3
  uriPrefix: /api
  url: 10.50.100.5/api

frontend:
  serviceName: todo-api-frontend
  labelApp: todo-frontend
  image: localhost:32000/todo-frontend:v1
  clusterIpPort: 8091
  clusterIpTargetPort: 80
  replicas: 3
  uriPrefix: /
  
istio:
  host: todo-app.com
  gateway:
    name: todo-app-gateway

prometheus:
  host: prometheus.todo-app.com
  serviceName: prometheus
  clusterIpPort: 9090
  
tls:
  issuerName: selfsigned-issuer
  issuerKind: Issuer
  email: example@gmail.com
  secretName: selfsigned-secret
  # certName: letsencrypt-certificate
