apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
  - hosts:
    - {{ .Values.frontend.domainName | indent 4}}
    - {{ .Values.api.domainName | indent 4}}
    secretName: letsencrypt-private-key
  rules:
  - host: {{ .Values.frontend.domainName }}
    http:
      paths:
        - path: /?(.*)
          pathType: Prefix
          backend:
            service:
              name: todo-frontend-service
              port:
                number: 8091
        - path: /prometheus
          pathType: Prefix
          backend:
            service:
              name: prom-service
              port:
                number: 9090
  - host: {{ .Values.api.domainName }}
    http:
      paths:
        - path: /?(.*)
          pathType: Prefix
          backend:
            service:
              name: todo-api-service
              port:
                number: 8080
