apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - 
    hosts:
    - {{ .Values.istio.host | indent 4 }} 
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - 
    hosts:
    - {{ .Values.istio.host | indent 4 }} 
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.tls.secretName }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-virtualservice
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.istio.host | indent 4 }}
  gateways:
    - {{ .Values.namespace }}/{{ .Values.istio.gateway.name }}
  http:
    - match:
      - uri:
          prefix:  {{ .Values.api.uriPrefix }}
      route:
        - destination:
            host: {{ .Values.api.serviceName }}
            port:
              number: {{ .Values.api.clusterIpPort }}
    - match:
      - uri:
          prefix: {{ .Values.frontend.uriPrefix }}
      route:
        - destination:
            host: {{ .Values.frontend.serviceName }}
            port:
              number: {{ .Values.frontend.clusterIpPort }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-virtualservice
  namespace: istio-system
spec:
  hosts:
    - {{ .Values.prometheus.host}}
  gateways:
    - {{ .Values.namespace }}/{{ .Values.istio.gateway.name }}
  http:
    - route:
      - destination:
          host: {{ .Values.prometheus.serviceName }}
          port:
            number: {{ .Values.prometheus.clusterIpPort }}

