apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: {{ .Values.istio.gateway.externalPort}}
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-virtualservice
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.istio.appVirtualService.host | indent 4}}
  gateways:
    - {{ .Values.namespace }}/{{ .Values.istio.gateway.name }}
  http:
    - match:
      - uri:
          prefix:  {{ .Values.api.uriPrefix }}
      route:
        - destination:
            host: {{ .Values.api.serviceName }}
            port:
              number: {{ .Values.api.clusterIpPort }}
    - match:
      - uri:
          prefix: {{ .Values.frontend.uriPrefix }}
      route:
        - destination:
            host: {{ .Values.frontend.serviceName }}
            port:
              number: {{ .Values.frontend.clusterIpPort }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-virtualservice
  namespace: istio-system
spec:
  hosts:
    - {{ .Values.prometheus.host}}
  gateways:
    - {{ .Values.namespace }}/{{ .Values.istio.gateway.name }}
  http:
    - route:
      - destination:
          host: {{ .Values.prometheus.serviceName }}
          port:
            number: {{ .Values.prometheus.clusterIpPort }}

