apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment
  labels:
    app: {{ .Values.frontend.labelApp }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.labelApp }}
  template: 
    metadata:
      labels:
        app: {{ .Values.frontend.labelApp }}
        version: {{ .Values.frontend.version }}
    spec:
      containers:
        - name: todo-frontend-container
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.clusterIpTargetPort }}
          env:
            - name: API_BASE_URL
              value: {{ .Values.api.url}}
{{ if .Values.frontend.useCanary true }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment-canary
  labels:
    app: {{ .Values.frontend.labelApp }}
spec:
  replicas: {{ .Values.frontend.canary.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.labelApp }}
  template: 
    metadata:
      labels:
        app: {{ .Values.frontend.labelApp }}
        version: {{ .Values.frontend.canary.version }}
    spec:
      containers:
        - name: todo-frontend-container
          image: {{ .Values.frontend.canary.image }}
          ports:
            - containerPort: {{ .Values.frontend.clusterIpTargetPort }}
          env:
            - name: API_BASE_URL
              value: {{ .Values.api.url}}
{{ end }} 
