apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment
  labels:
    app: {{ .Values.frontend.labelApp }}
spec:
  replicas: {{ .Values.frontend.repicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.labelApp }}
  template: 
    metadata:
      labels:
        app: {{ .Values.frontend.labelApp }}
    spec:
      containers:
        - name: todo-frontend-container
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.clusterIpTargetPort }}
          env:
            - name: API_BASE_URL
              value: {{ .Values.api.url}}
