apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  labels:
    app: {{ .Values.frontend.labelApp }}
    service: {{ .Values.frontend.labelApp }}
spec: 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.clusterIpPort }}
      targetPort: {{ .Values.frontend.clusterIpTargetPort }}
  selector: 
    app: {{ .Values.frontend.labelApp }}
