apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  labels:
    app: {{ .Values.frontend.labelApp }}
    service: {{ .Values.frontend.labelApp }}
spec: 
  type: {{ .Values.frontend.serviceType }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.targetPort }}
  selector: 
    app: {{ .Values.frontend.labelApp }}
