apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  labels:
    app: todo-frontend
    service: todo-frontend
spec: 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 80
  selector: 
    app: todo-frontend

