apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment-canary
  labels:
    app: {{ .Values.frontend.labelApp }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.labelApp }}
  template: 
    metadata:
      labels:
        app: {{ .Values.frontend.labelApp }}
        version: v2
    spec:
      containers:
        - name: todo-frontend-container
          image: {{ .Values.frontend.canaryImage }}
          ports:
            - containerPort: {{ .Values.frontend.clusterIpTargetPort }}
          env:
            - name: API_BASE_URL
              value: {{ .Values.api.url}}
