apiVersion: v1
kind: Service
metadata:
  name: todo_api_service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.todo_api.port }}
      targetPort: {{ .Values.todo_api.targetPort }}
  selector:
    app: todo_api
