apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo_api_deployment
  labels:
    app: todo_api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo_api
  template:
    metadata:
      labels:
        app: todo_api
    spec:
      containers:
        - name: {{ .Values.todo_api.container.name }}
          image: {{ .Values.todo_api.container.image }}
          ports:
            - containerPort: {{ .Values.todo_api.port }}
          env:
            - name: TODO_DB_USER
              value: {{ .Values.todo_api.database.user }}
            - name: TODO_DB_PASSWD
              value: {{ .Values.todo_api.database.password }}
            - name: TODO_DB_HOST
              value: {{ .Values.todo_api.database.host }}
            - name: TODO_DB_PORT
              value: {{ .Values.todo_api.database.port }}
            - name: TODO_DB_NAME
              value: {{ .Values.todo_api.database.name }}
            - name: TODO_PORT
              value: {{ .Values.todo_api.port }}
