apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: {{ .Values.database.labelApp }}
spec:
  ports:
  - port: {{ .Values.database.port }}
  selector:
    app: {{ .Values.database.labelApp }}
  clusterIP: None
