apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: "standard"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: todo-mysql-storage #make sure that this gce presistentDisk already exist in the cloud
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: {{ .Values.database.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
