apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: {{ .Values.database.labelApp }}
data:
  MYSQL_DATABASE: {{ .Values.database.name}}
  MYSQL_USER: {{ .Values.database.user}}
