apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  labels:
    app: {{ .Values.api.labelApp }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.labelApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.labelApp }}
    spec:
      containers:
        - name: todo-api-container
          image: {{ .Values.api.image }}
          ports:
            - containerPort: {{ .Values.api.targetPort}}
              protocol: TCP
          env:
            - name: TODO_DB_USER
              value: {{ .Values.database.user }}
            - name: TODO_DB_HOST
              value: {{ .Values.database.host }}
            - name: TODO_DB_PORT
              value: {{ quote .Values.database.port }}
            - name: TODO_DB_NAME
              value: {{ .Values.database.name }}
            - name: TODO_PORT
              value: {{ quote .Values.api.targetPort}}
            - name: TODO_DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
