apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  labels:
    app: todo-api
    service: todo-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.todoApi.port }}
    targetPort: {{ .Values.todoApi.targetPort }}
  selector:
    app: todo-api
