apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.serviceName }}
  labels:
    app: {{ .Values.api.labelApp }}
    service: {{ .Values.api.labelApp }}
  annotations:
    cloud.google.com/backend-config: '{"default": "api-backend-config"}'
spec:
  type: {{ .Values.api.serviceType }}
  ports:
  - protocol: TCP
    port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.targetPort }}
  selector:
    app: {{ .Values.api.labelApp }}
