apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-api-deployment
  labels:
    app: todo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api-container
          image: {{ .Values.todoApi.image }}
          ports:
            - containerPort: {{ .Values.todoApi.port }}
          env:
            - name: TODO_DB_USER
              value: {{ .Values.database.user }}
            - name: TODO_DB_PASSWD
              value: {{ .Values.database.password }}
            - name: TODO_DB_HOST
              value: {{ .Values.database.host }}
            - name: TODO_DB_PORT
              value: {{ quote .Values.database.port }}
            - name: TODO_DB_NAME
              value: {{ .Values.database.name }}
            - name: TODO_PORT
              value: {{ quote .Values.todoApi.port }}
