apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.serviceName }}
  labels:
    app: {{ .Values.api.labelApp }}
    service: {{ .Values.api.labelApp }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.api.clusterIpPort }}
    targetPort: {{ .Values.api.clusterIpTargetPort }}
  selector:
    app: {{ .Values.api.labelApp }}
