apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
  namespace: monitoring
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/opt/prom/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
  namespace: monitoring
spec:
  storageClassName: microk8s-hostpath
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
